/* tslint:disable */
// @ts-nocheck
const { writeFileSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;

const supportedEnvironments = ['dev', 'prod', 'test'];
if (!supportedEnvironments.includes(environment)) {
  throw new Error(`Unsupported environment "${environment}". Expected one of: ${supportedEnvironments.join(', ')}.`);
}

const requiredVariables = [
  'BASE',
  'BASE_URL',
  'BASE_URL_CORD_APP',
  'BASE_URL_LEGACY',
  'MIND_MAP_URL',
  'NOTIFICATION_URL',
  'SOCKET_URL',
  'CAPTCHA_SITE_KEY',
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'WEB_RTC_SDK_SERVER_URL',
  'WEB_RTC_TOKEN_SERVER_URL',
  'SITE_KEY',
  'EXTERNAL_PRESCRIPTION_CRED',
  'VAPID_PUBLIC_KEY',
  'AUTH_GATE_WAY_URL',
  'SHOW_CAPTCHA'
];

const missingVariables = requiredVariables.filter((name) => {
  const value = process.env[name];
  return value === undefined || value.trim() === '';
});

if (missingVariables.length) {
  throw new Error(`Missing required environment variables: ${missingVariables.join(', ')}.`);
}

const showCaptchaValue = String(process.env.SHOW_CAPTCHA).toLowerCase();
if (!['true', 'false'].includes(showCaptchaValue)) {
  throw new Error('SHOW_CAPTCHA must be either "true" or "false".');
}

const envDirectory = './src/environments';
mkdirSync(envDirectory, { recursive: true });

const createEnvironment = (production) => ({
  production,
  base: process.env.BASE,
  baseURL: process.env.BASE_URL,
  baseURLCoreApp: process.env.BASE_URL_CORD_APP,
  baseURLLegacy: process.env.BASE_URL_LEGACY,
  mindmapURL: process.env.MIND_MAP_URL,
  notificationURL: process.env.NOTIFICATION_URL,
  socketURL: process.env.SOCKET_URL,
  captchaSiteKey: process.env.CAPTCHA_SITE_KEY,
  firebase: {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID
  },
  webrtcSdkServerUrl: process.env.WEB_RTC_SDK_SERVER_URL,
  webrtcTokenServerUrl: process.env.WEB_RTC_TOKEN_SERVER_URL,
  siteKey: process.env.SITE_KEY,
  externalPrescriptionCred: process.env.EXTERNAL_PRESCRIPTION_CRED,
  vapidPublicKey: process.env.VAPID_PUBLIC_KEY,
  authGatwayURL: process.env.AUTH_GATE_WAY_URL,
  showCaptcha: environment === 'test' ? false : showCaptchaValue === 'true',
  recordsPerPage: 1000
});

const environmentFileContent = (production) => `// This file is generated by src/assets/scripts/setEnv.ts. Do not edit or commit it.
export const environment = ${JSON.stringify(createEnvironment(production), null, 2)};
`;

writeFileSync(
  `${envDirectory}/environment.ts`,
  environmentFileContent(false),
  { encoding: 'utf8' }
);
writeFileSync(
  `${envDirectory}/environment.prod.ts`,
  environmentFileContent(true),
  { encoding: 'utf8' }
);

console.log(`Generated Angular environment files for ${environment}.`);

/* tslint:enable */
